### ISSUE TITLE
cx_Freeze error

### ISSUE THREAD

**Issue by Sikksens** [th3-z/fb2k-mini-player#1]
I keep getting this error when trying to launch

![FoobarMiniplayer_2019-12-16_02-33-18](https://user-images.githubusercontent.com/15923337/70871923-8b4aea00-1fac-11ea-92cd-70a24b379ec2.png)

**Comment by z3ath** [comment]
Hi,
Thanks for raising this issue. I don't have the tools immediately available to properly debug this. Nevertheless I've had a go at fixing it and made another release (untested).

See if the new release works for you, if it doesn't I'll get windows/fb2k/fb2k-com setup later today to have another go at it.

I didn't think anyone would be interested in using this. Its pretty neat though, its great if you only have a single monitor and want to control/monitor fb2k while in borderless fs.

**Comment by Sikksens** [comment]
Thanks so much for the quick fix, it's working perfectly now!!

Ya it's really what I was looking for, I have a second monitor and wanted to see song details and media controls but couldn't get a small layout to look good in fb2k.

Got it fitted nicely on the taskbar now :D
![2019-12-16_16-37-23](https://user-images.githubusercontent.com/15923337/70915342-5bd6c480-2022-11ea-92a5-866527b27961.png)

Also would it be possible at all to pull artist or album images to the first square with the logo?

**Comment by z3ath** [comment]
Good to see that its working again. 

It does already try to find the artwork and display it there, it must of missed it in this case. It will try to find artwork in the track metadata, and neighboring image files that are in a set of names. The set of names it considers to be artwork are as follows: `"folder.jpg", folder.png", "folder.gif", "cover.png", "cover.jpg", "cover.gif", "front.jpg", "front.png", "front.gif"`.

There could be some improvement in the artwork discovery I think. If you could provide more details about your non-working example (filenames, format) I can have a look at it.

**Comment by Sikksens** [comment]
Ah of course, I forgot I was trying an internet radio stream and it wasn't pulling it, I see now with a local song it does indeed work, I think for radio stream I use a spider monkey or wsh panel to cache the song albums images but not sure if that will be easily accessible?

**Comment by z3ath** [comment]
Ah, I don't think getting artwork for radio streams will be easy. 

It's been a while since I worked on this but I'm pretty sure I can't get the artwork from fb2k via the COM automation plugin, the miniplayer has to get the artwork itself.

It would be possible to get the artwork from a third party service or cache but I think it'd be more trouble than it's worth. That said, I'm not really familiar with what solutions are available.

[Application.get_art()](https://github.com/th3-z/fb2k-mini-player/blob/master/FoobarMiniplayer.py#L239) is the relevant function if you want to have a go at it. This should be called every time the song changes, even when listening to a radio.
